### ISSUE TITLE
Repo topics

### ISSUE THREAD

**Issue by maelle** [ropensci/EndoMineR#2]
:wave: @sebastiz!

I added a few topics to the GitHub repo, see below

![image](https://user-images.githubusercontent.com/8360597/40723413-2e47da92-641f-11e8-923e-815af503e9c1.png)

Please modify as you wish. Please let "r" and "rstats" unless you have very strong feelings against them, because they help making your repo discoverable via GitHub browsing (even if the repo has the right language). Thanks!

**Comment by sebastiz** [comment]
@maelle apologies forgot to say thanks. All done

**Comment by maelle** [comment]
No problem, great!
