### ISSUE TITLE
Two 'Remotes'  in DESCRIPTION file

### ISSUE THREAD

**Issue by sckott** [ropensci/EndoMineR#70]
https://github.com/ropensci/EndoMineR/blob/master/DESCRIPTION#L49-L52

you can only have one AFAIK https://cloud.r-project.org/web/packages/remotes/vignettes/dependencies.html

**Comment by sebastiz** [comment]
Thanks @sckott Think I've fixed it

**Comment by sckott** [comment]
yep, looks right

**Comment by jeroen** [comment]
Do you really need the dev version of rlang? This is causing some problems for other packages.

**Comment by sebastiz** [comment]
Seems to not cause any problems with me so I'd rather leave it as is for now.
