### ISSUE TITLE
Failing to install due to unavailable dependency

### ISSUE THREAD

**Issue by tomjemmett** [ropensci/EndoMineR#82]
While trying to install this package I'm getting errors relating to [ggplus](https://github.com/guiastrennec/ggplus) not being available to install. This package does not appear to be on cran, and the github repository suggests that this package has been abandoned as it no longer works with ggplot2 >= 2.2.0.

Looks like this package is only used once ([R/Graphics.R#L415](https://github.com/ropensci/EndoMineR/blob/eca2b24fbab1bd70e38069f427a113e2c49e0a86/R/Graphics.R#L415)).

The recommendation from ggplus is
> As an alternative I suggest that you use the very good facet_wrap_paginate() or facet_grid_paginate() from the ggforce package.

If this is resolved I can add the package to [https://nhs-r-community.r-universe.dev/ui#builds](nhs-r-community.r-universe.dev).

**Comment by sebastiz** [comment]
Thanks for this I’ll get on to it

Sebastian

On 13 Jul 2021, at 10:58, Tom Jemmett ***@***.***> wrote:

﻿

While trying to install this package I'm getting errors relating to ggplus<https://github.com/guiastrennec/ggplus> not being available to install. This package does not appear to be on cran, and the github repository suggests that this package has been abandoned as it no longer works with ggplot2 >= 2.2.0.

Looks like this package is only used once (R/Graphics.R#L415<https://github.com/ropensci/EndoMineR/blob/eca2b24fbab1bd70e38069f427a113e2c49e0a86/R/Graphics.R#L415>).

The recommendation from ggplus is

As an alternative I suggest that you use the very good facet_wrap_paginate() or facet_grid_paginate() from the ggforce package.

If this is resolved I can add the package to https://nhs-r-community.r-universe.dev/ui#builds<nhs-r-community.r-universe.dev>.

**Comment by sebastiz** [comment]
Hi @tomjemmett this has been fixed with the removal of pagination so that the end user can paginate if desired.

**Comment by jeroen** [comment]
Hello! The `ggplus` dependency is still in your [DESCRIPTION](https://github.com/ropensci/EndoMineR/blob/HEAD/DESCRIPTION) and [NAMESPACE](https://github.com/ropensci/EndoMineR/blob/HEAD/DESCRIPTION) file, which causes the package to fail installing: see https://ropensci.r-universe.dev

If ggplus is no longer needed, could you remove it from the DESCRIPTION and NAMESPACE files?

**Comment by sebastiz** [comment]
Thanks for pointing it out. I've amended both files accordingly
